# Užitočné zdroje

## Odkazy 
### sk
- videokurz od Yablka: [Git a Github od základov](https://www.youtube.com/watch?v=0v5K4GvK4Gs)
- videokurz na kanáli [Informatika s Mišom](https://www.youtube.com/playlist?list=PLNAMH_0HgWT-ey31hQqrmi_Rgr4OVWgH3)
- predmet *Základy softvérového inžinierstva* na FEI TUKE
    - časť 2: [Systémy pre správu verzií](https://kurzy.kpi.fei.tuke.sk/zsi/labs/02-git.html)
    - časť 3: [Práca s vetvami v systéme Git](https://kurzy.kpi.fei.tuke.sk/zsi/labs/03-git.html)

## Odkazy 
### en
- *[Pro Git](https://git-scm.com/book/en/v2)*, voľne dostupná oficiálna kniha, k dispozícii čiastočne aj [v češtine](https://git-scm.com/book/cs/v2)
- [git - the simple guide](https://rogerdudler.github.io/git-guide/)
- [Git tutoriály](https://www.atlassian.com/git/tutorials) od Atlassianu
- Coursera: [Introduction to Git and GitHub](https://www.coursera.org/learn/introduction-git-github/)
- Missing Semester of CS Education, [Lecture 6: Version Control (git)](https://www.youtube.com/watch?v=2sjqTHE0zok)
- [Learn how Git works internally with simple diagrams](https://medium.com/@praveenmuth2/learn-how-git-works-internally-with-simple-diagrams-a9349dc32831)
- [Markdown Guide](https://www.markdownguide.org/)
- [Learn Markdown in 5 minutes](https://manan-tank.medium.com/learn-markdown-in-5-minutes-7cc01405495e)


## Git slovník

::: {.columns}

::: {.column width="50%" .git-slovnik}
| en | sk |
|---|---|
| *branch*              | vetva |
| *clone*               | naklonovanie repozitára |
| *commit*              | záznam |
| *commit message*      | popis záznamu |
| *conflict*            | konflikt medzi verziami |
| *conflict resolution* | riešenie konfliktov |
| *diff*                | rozdiel medzi verziami |
| *merge*               | zlúčenie vetiev |
:::

::: {.column width="50%" .git-slovnik}
| en | sk |
|---|---|
| *pull*                | stiahnutie vzdialených zmien |
| *push*                | odoslanie lokálnych zmien |
| *repository*          | repozitár, úložisko |
| *remote*              | vzdialený repozitár |
| *snapshot*            | snímka |
| *staging area*        | prípravná oblasť (tiež *index*) |
| *status*              | stav repozitára |
| *version*             | verzia |
:::

:::